apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: nfs-storage
provisioner: csi-nfsplugin
parameters:
  server: 192.168.73.184
  share: /nfs/data
  archiveOnDelete: "false"
